apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: chartmuseum
spec:
  releaseName: chartmuseum
  interval: 1h0m0s
  timeout: 5m
  chart:
    spec:
      chart: chartmuseum
      version: '<4.0.0'
      sourceRef:
        kind: HelmRepository
        name: chartmuseum-external
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    serviceAccount:
      create: true
    securityContext:
      runAsNonRoot: true
    service:
      servicename: chartmuseum
      externalPort: 80
      type: NodePort
      nodePort: 30002
    env:
      open:
        DISABLE_API: false
    persistence:
      enabled: false
