apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
spec:
  interval: 1h0m0s
  provider: generic
  url: https://charts.bitnami.com/bitnami
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jetstack
spec:
  interval: 1h0m0s
  provider: generic
  url: https://charts.jetstack.io
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: chartmuseum-external
spec:
  interval: 1m0s
  provider: generic
  url: https://chartmuseum.github.io/charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: chartmuseum
spec:
  interval: 1m00s
  provider: generic
  url: http://chartmuseum.default
