apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helm-repositories.yaml
- metrics-server.yaml
- cert-manager.yaml
- mysql.yaml
- minio.yaml
- chartmuseum.yaml
- backup-operator.yaml
