apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  releaseName: cert-manager
  interval: 1h0m0s
  timeout: 5m
  chart:
    spec:
      chart: cert-manager
      version: v1.14.2
      sourceRef:
        kind: HelmRepository
        name: jetstack
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    installCRDs: true
    nameOverride: cert-manager
    fullnameOverride: cert-manager
    replicaCount: 1
    enableCertificateOwnerRef: true
    prometheus:
      enabled: false
