apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
spec:
  releaseName: metrics-server
  interval: 1h0m0s
  timeout: 5m
  chart:
    spec:
      chart: metrics-server
      version: '<7.0.0'
      sourceRef:
        kind: HelmRepository
        name: bitnami
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    nameOverride: metrics-server
    fullnameOverride: metrics-server
    extraArgs:
      - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
      - --metric-resolution=15s
      - --kubelet-insecure-tls
    apiService:
      create: true
    resources:
      limits:
        memory: 75Mi
      requests:
        cpu: 50m
        memory: 75Mi
    podSecurityContext:
      enabled: true
    containerSecurityContext:
      enabled: true
      readOnlyRootFilesystem: false
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
