apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
spec:
  releaseName: minio
  interval: 1h0m0s
  timeout: 5m
  chart:
    spec:
      chart: minio
      version: '<13.0.0'
      sourceRef:
        kind: HelmRepository
        name: bitnami
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    nameOverride: minio
    fullnameOverride: minio
    disableWebUI: false
    auth:
      rootUser: minio
      rootPassword: miniominio
    defaultBuckets: backups
    persistence:
      enabled: false
    service:
      type: NodePort
      nodePorts:
        api: 30000
        console: 30001
    serviceAccount:
      automountServiceAccountToken: false
    metrics:
      serviceMonitor:
        enabled: false
      prometheusRule:
        enabled: false
