apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mysql
spec:
  releaseName: mysql
  interval: 1h0m0s
  timeout: 5m
  chart:
    spec:
      chart: mysql
      version: '<10.0.0'
      sourceRef:
        kind: HelmRepository
        name: bitnami
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    nameOverride: mysql
    fullnameOverride: mysql
    auth:
      rootPassword: root
      username: mysql
      password: mysql
      database: default
    primary:
      persistence:
        enabled: false
