#  ┬─┐┬─┐┬─┐  ┌─┐┌─┐┌┌┐┌┌┐o┌┐┐
#  │─┘│┬┘├─ ──│  │ ││││││││ │ 
#  ┘  ┘└┘┴─┘  └─┘┘─┘┘ ┘┘ ┘┘ ┘ 

repos:
- repo: https://github.com/zricethezav/gitleaks
  rev: v8.15.2
  hooks:
  - id: gitleaks
    args:
    - --config=gitleaks.toml
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-merge-conflict
    - id: end-of-file-fixer
- repo: local
  hooks:
    - id: inkscape-anonimize
      name: Inkscape Anonimize
      entry: etc/anonymize.sh
      language: script
      files: ^etc/logo.svg$
      types: [file]
      pass_filenames: true
