apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
- path: schedule.yaml
  target:
    kind: BackupSchedule
- path: run.yaml
  target:
    kind: BackupRun
- patch: |-
    - op: replace
      path: /spec/retainPolicy
      value: Retain
  target:
    kind: BackupRun
    name: '.+106.+'
