{{- if .Values.rbac.create }}
# permissions for end users to view backupruns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backuprun-viewer-role
  labels:
    {{- include "backup-operator.labels" $ | nindent 4 }}
rules:
- apiGroups:
  - backup-operator.io
  resources:
  - backupruns
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - backup-operator.io
  resources:
  - backupruns/status
  verbs:
  - get
{{- end -}}
