{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backup-operator-manager-leader-election
  labels:
    {{- include "backup-operator.labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: backup-operator-manager-leader-election
subjects:
- kind: ServiceAccount
  name: {{ include "backup-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
