{{- if .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backup-operator-manager
  labels:
    {{- include "backup-operator.labels" $ | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - backup-operator.io
  resources:
  - backupruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - backup-operator.io
  resources:
  - backupruns/finalizers
  verbs:
  - update
- apiGroups:
  - backup-operator.io
  resources:
  - backupruns/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - backup-operator.io
  resources:
  - backupschedules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - backup-operator.io
  resources:
  - backupschedules/finalizers
  verbs:
  - update
- apiGroups:
  - backup-operator.io
  resources:
  - backupschedules/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - backup-operator.io
  resources:
  - backupstorages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - backup-operator.io
  resources:
  - backupstorages/finalizers
  verbs:
  - update
- apiGroups:
  - backup-operator.io
  resources:
  - backupstorages/status
  verbs:
  - get
  - patch
  - update
{{- end -}}
