apiVersion: backup-operator.io/v1
kind: BackupSchedule
metadata:
  name: only-compression
spec:
  ## This is a BackupRun spec part
  template:
    spec:
      storage:
        # Sprig templated string that must produce a valid path to result backup file in storage
        # See http://masterminds.github.io/sprig/.
        path: /mysql/101-{{ now | date "2006.01.02-15:04:05" }}.sql.gz
      compression:
        # Compression block is optional
        algorithm: gzip
        level: 9
      # Command for pod exec for making a backup
      backup:
        # It must complete in 5 minutes (deadline is optional)
        deadlineSeconds: 300
        # Name of pod container that we use as a target for pod exec
        container: mysql
        command: ["/bin/sh", "-c"]
        args:
        # Backup must be streamed to STDOUT
        - mysqldump -h mysql.default -u mysql "-p${MYSQL_PASSWORD}" default
      # Command for pod exec for making a restoration. This one is optional.
      restore:
        deadlineSeconds: 300
        container: mysql
        command: ["/bin/sh", "-c"]
        args:
        # Backup data will be passed to STDIN
        - mysql -h mysql.default -u mysql "-p${MYSQL_PASSWORD}" default
