{
 "title": "Backup Operator",
 "tags": [ "backup" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_node_info,cluster)"
    }
   },
   {
    "name": "storage",
    "label": "Storage",
    "query": {
     "query": "label_values(backup_operator_storage_status{cluster=~\"$cluster\"},name)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(backup_operator_schedule_status{cluster=~\"$cluster\", storage=~\"$storage\"},namespace)"
    }
   },
   {
    "name": "schedule",
    "label": "Schedule",
    "query": {
     "query": "label_values(backup_operator_schedule_status{namespace=~\"$namespace\", storage=~\"$storage\", cluster=~\"$cluster\"},name)"
    }
   },
   { "name": "ad_hoc", "label": "Filters" }
  ]
 },
 "panels": [
  { "title": "Storage / $storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "storage" },
  {
   "title": "Total Schedules",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(backup_operator_schedule_status{cluster=~\"$cluster\", storage=~\"$storage\", namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Runs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(backup_operator_run_status{cluster=~\"$cluster\", namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful Runs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(backup_operator_run_status{cluster=~\"$cluster\", namespace=~\"$namespace\", state=~\".*Successful.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Runs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(backup_operator_run_status{cluster=~\"$cluster\", namespace=~\"$namespace\", state=~\".*Failed.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(backup_operator_run_backup_size_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\"} * on(cluster, namespace, name) group_left(storage) (backup_operator_run_status{cluster=~\"$cluster\", namespace=~\"$namespace\"}*0+1))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Schedules size",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (schedule) (backup_operator_run_backup_size_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\"} * on(cluster, namespace, name) group_left(storage, schedule) (backup_operator_run_status{cluster=~\"$cluster\", namespace=~\"$namespace\", schedule=~\"$schedule\"}*0+1))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Schedule / $schedule",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "repeat": "schedule",
   "collapsed": true,
   "panels": [
    {
     "title": "Total Runs",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(backup_operator_run_status{cluster=~\"$cluster\", namespace=~\"$namespace\", schedule=~\"$schedule\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Successful Runs",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 3, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(backup_operator_run_status{cluster=~\"$cluster\", namespace=~\"$namespace\", schedule=~\"$schedule\", state=~\".*Successful.*\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failed Runs",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 6, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(backup_operator_run_status{cluster=~\"$cluster\", namespace=~\"$namespace\", schedule=~\"$schedule\", state=~\".*Failed.*\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total size",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 9, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(backup_operator_run_backup_size_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\"} * on(cluster, namespace, name) group_left(storage) (backup_operator_run_status{cluster=~\"$cluster\", namespace=~\"$namespace\", schedule=~\"$schedule\"}*0+1))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Backup Runs",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (name) (backup_operator_run_backup_size_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\"} * on(namespace, name) group_left(storage) (backup_operator_run_status{cluster=~\"$cluster\", namespace=~\"$namespace\", schedule=~\"$schedule\"}*0+1))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (name) (time() - backup_operator_run_status{cluster=~\"$cluster\", namespace=~\"$namespace\", schedule=~\"$schedule\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}