apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: working-
resources:
- 100_encryption_compression
- 101_only_compression
- 102_only_encryption
- 103_encryption_wtih_restore
- 104_plain_backup_restore
- 105_only_backup
- 106_only_restore
