apiVersion: backup-operator.io/v1
kind: BackupSchedule
metadata:
  name: broken-no-job
spec:
  ## This is a BackupRun spec part
  template:
    spec:
      storage:
        # Sprig templated string that must produce a valid path to result backup file in storage
        # See http://masterminds.github.io/sprig/.
        path: /mysql/{{ now | date "2006.01.02-15:04:05" }}.sql.gz.age
      compression:
        # Compression block is optional
        algorithm: gzip
        level: 9
      encryption:
        # Encryption block is optional
        # Encryption is always performed after the compression if it is enabled
        # Encrypted with https://github.com/FiloSottile/age
        recipients:
        - age1vmk6z84kftwfupt2s38zqf78ft8s7k8khl5wzzhjeglwrndsafnq52msn2 # My key
        - age1mcuu74eh4gmpnhdxx2tkqdfjyl0gwxefux6w4hyxwzt3lej7qf7qh5cga6 # Sample key
        # If you want this backup to be automatically restorable and it is encrypted,
        #  you must provide decryption key as well (obviously)
        decryptionKey:
          name: age
          key: age
