{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "backup-operator.serviceAccountName" . }}
  labels:
    {{- include "backup-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with .Values.serviceAccount.spec }}
{{- toYaml . | nindent 0 }}
{{- end }}
{{- end }}
