version: "3"

tasks:
  install:
    desc: Install mkdocs and required plugins
    cmds:
      - python3 -m pip install --upgrade mkdocs-material
      - mkdocs get-deps | xargs python3 -m pip install --upgrade

  build:
    desc: Build mkdocs site
    cmds:
      - mkdocs build

  serve:
    desc: Serve mkdocs on 127.0.0.1:8000
    cmds:
      - mkdocs serve
