apiVersion: backup-operator.io/v1
kind: BackupRun
metadata:
  labels:
    app.kubernetes.io/name: backupschedule
    app.kubernetes.io/instance: backupschedule-sample
    app.kubernetes.io/part-of: backup-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: backup-operator
  name: only-restore
spec:
  # Retain controls whether backup will be deleted from storage on BackupRun removal
  retainPolicy: Retain
  storage:
    # Name of BackupStorage resource
    name: backupstorage-sample
    # Sprig templated string that must produce a valid path to result backup file in storage
    # See http://masterminds.github.io/sprig/.
    path: /mysql/70-only-backup.sql
  # Command for pod exec for making a restoration. This one is optional.
  restore:
    deadlineSeconds: 300
    container: mysql
    command: ["/bin/sh", "-c"]
    args:
    # Backup data will be passed to STDIN
    - mysql -h mysql.default -u mysql "-p${MYSQL_PASSWORD}" default
  template:
    # Optionally you can setup custom labels and annotations for Pod
    metadata:
      labels:
        custom: label
      annotations:
        and: annotation
    # Standard Pod spec
    spec:
      restartPolicy: Never
      containers:
      - name: mysql
        image: docker.io/bitnami/mysql:8.0.34-debian-11-r75
        command: ["sleep", "1d"]
        env:
        # If you need any secrets - mount them yourself
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: mysql-password
