# permissions for end users to edit backupruns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: backuprun-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: backup-operator
    app.kubernetes.io/part-of: backup-operator
    app.kubernetes.io/managed-by: kustomize
  name: backuprun-editor-role
rules:
- apiGroups:
  - backup-operator.io
  resources:
  - backupruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - backup-operator.io
  resources:
  - backupruns/status
  verbs:
  - get
