#  ┬ ┬┬─┐┬  ┌┌┐
#  │─┤├─ │  │││
#  ┘ ┴┴─┘┘─┘┘ ┘

name: Helm

on:
  # Runs on pushes targeting the default branch
  push:
    tags:
      - "v*"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      tag:
        description: Version tag
        required: true
        type: string

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: helm
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  # Build job
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Update chart appVersion
        uses: mikefarah/yq@v4
        with:
          cmd: |-
            VERSION="${TAG#v}"
            yq -i '.appVersion = strenv(VERSION)' charts/backup-operator/Chart.yaml
        env:
          TAG: ${{ inputs.tag }}
          # TAG: ${{ github.ref_name }}

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          mark_as_latest: true
          pages_branch: helm-charts
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CR_GIT_REPO: ${{ github.repository }}
